from tables import Spindle, Grid, association_table, SpindleRunIn, RunInData, Session

import pymysql
from sqlalchemy import exc
from sqlalchemy import func

# --------------------------

s = Session()

new_spindle_runin = SpindleRunIn(
  spindleRunIn_excel_file = 'Report_2022_12_16_15_4936.xlsx',
  spindleRunIn_customer = 'BB2095',
  spindleRunIn_work_id = '2022446',
  spindleRunIn_spindle_id = 11,     #主軸 THG-150.01
  spindleRunIn_employer = 4,        #員工 0059, 吳發財
  spindleRunIn_date = '2022-11-30',
)
s.add(new_spindle_runin)

try:
    s.commit()
except pymysql.err.IntegrityError as e:
    s.rollback()
except exc.IntegrityError as e:
    s.rollback()
except Exception as e:
    s.rollback()

print("insert SpindleRunIn data is ok...")

# --------------------------

_obj= [
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:05:41', 'spindleRunIn_speed_level': 1, 'spindleRunIn_speed': 1000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 44.4, 'spindleRunIn_outer_backBearing_temp': 26.3, 'spindleRunIn_room_temp': 26.4, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.033, 'spindleRunIn_frontBearing_vibration_acc1': 0.066, 'spindleRunIn_frontBearing_vibration_disp1': 0.5, 'spindleRunIn_frontBearing_vibration_speed2': 0.032, 'spindleRunIn_frontBearing_vibration_acc2': 0.063, 'spindleRunIn_frontBearing_vibration_disp2': 0.3, 'spindleRunIn_backBearing_vibration_speed1': 0.015, 'spindleRunIn_backBearing_vibration_acc1': 0.093, 'spindleRunIn_backBearing_vibration_disp1': 0.2, 'spindleRunIn_backBearing_vibration_speed2': 0.029, 'spindleRunIn_backBearing_vibration_acc2': 0.087, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:05:55', 'spindleRunIn_speed_level': 2, 'spindleRunIn_speed': 2000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 44.3, 'spindleRunIn_outer_backBearing_temp': 26.2, 'spindleRunIn_room_temp': 26.3, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.022, 'spindleRunIn_frontBearing_vibration_acc1': 0.076, 'spindleRunIn_frontBearing_vibration_disp1': 0.3, 'spindleRunIn_frontBearing_vibration_speed2': 0.026, 'spindleRunIn_frontBearing_vibration_acc2': 0.065, 'spindleRunIn_frontBearing_vibration_disp2': 0.2, 'spindleRunIn_backBearing_vibration_speed1': 0.021, 'spindleRunIn_backBearing_vibration_acc1': 0.098, 'spindleRunIn_backBearing_vibration_disp1': 0.2, 'spindleRunIn_backBearing_vibration_speed2': 0.025, 'spindleRunIn_backBearing_vibration_acc2': 0.09, 'spindleRunIn_backBearing_vibration_disp2': 0.1 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:06:09', 'spindleRunIn_speed_level': 3, 'spindleRunIn_speed': 3000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 44.3, 'spindleRunIn_outer_backBearing_temp': 26.2, 'spindleRunIn_room_temp': 26.2, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.028, 'spindleRunIn_frontBearing_vibration_acc1': 0.08, 'spindleRunIn_frontBearing_vibration_disp1': 0.3, 'spindleRunIn_frontBearing_vibration_speed2': 0.025, 'spindleRunIn_frontBearing_vibration_acc2': 0.064, 'spindleRunIn_frontBearing_vibration_disp2': 0.2, 'spindleRunIn_backBearing_vibration_speed1': 0.038, 'spindleRunIn_backBearing_vibration_acc1': 0.099, 'spindleRunIn_backBearing_vibration_disp1': 0.2, 'spindleRunIn_backBearing_vibration_speed2': 0.022, 'spindleRunIn_backBearing_vibration_acc2': 0.09, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:06:22', 'spindleRunIn_speed_level': 4, 'spindleRunIn_speed': 4000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 44.3, 'spindleRunIn_outer_backBearing_temp': 26.2, 'spindleRunIn_room_temp': 26.1, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.067, 'spindleRunIn_frontBearing_vibration_acc1': 0.084, 'spindleRunIn_frontBearing_vibration_disp1': 0.3, 'spindleRunIn_frontBearing_vibration_speed2': 0.043, 'spindleRunIn_frontBearing_vibration_acc2': 0.065, 'spindleRunIn_frontBearing_vibration_disp2': 17, 'spindleRunIn_backBearing_vibration_speed1': 0.051, 'spindleRunIn_backBearing_vibration_acc1': 0.096, 'spindleRunIn_backBearing_vibration_disp1': 0.2, 'spindleRunIn_backBearing_vibration_speed2': 0.04, 'spindleRunIn_backBearing_vibration_acc2': 0.09, 'spindleRunIn_backBearing_vibration_disp2': 19.5 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:06:35', 'spindleRunIn_speed_level': 5, 'spindleRunIn_speed': 5000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 44.2, 'spindleRunIn_outer_backBearing_temp': 26.2, 'spindleRunIn_room_temp': 26.1, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.052, 'spindleRunIn_frontBearing_vibration_acc1': 0.075, 'spindleRunIn_frontBearing_vibration_disp1': 0.3, 'spindleRunIn_frontBearing_vibration_speed2': 0.026, 'spindleRunIn_frontBearing_vibration_acc2': 0.065, 'spindleRunIn_frontBearing_vibration_disp2': 0.2, 'spindleRunIn_backBearing_vibration_speed1': 0.058, 'spindleRunIn_backBearing_vibration_acc1': 0.096, 'spindleRunIn_backBearing_vibration_disp1': 0.2, 'spindleRunIn_backBearing_vibration_speed2': 0.021, 'spindleRunIn_backBearing_vibration_acc2': 0.09, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:06:48', 'spindleRunIn_speed_level': 6, 'spindleRunIn_speed': 6000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 44.2, 'spindleRunIn_outer_backBearing_temp': 26.1, 'spindleRunIn_room_temp': 26, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.06, 'spindleRunIn_frontBearing_vibration_acc1': 0.094, 'spindleRunIn_frontBearing_vibration_disp1': 0.3, 'spindleRunIn_frontBearing_vibration_speed2': 0.03, 'spindleRunIn_frontBearing_vibration_acc2': 0.069, 'spindleRunIn_frontBearing_vibration_disp2': 0.2, 'spindleRunIn_backBearing_vibration_speed1': 0.069, 'spindleRunIn_backBearing_vibration_acc1': 0.11, 'spindleRunIn_backBearing_vibration_disp1': 0.3, 'spindleRunIn_backBearing_vibration_speed2': 0.025, 'spindleRunIn_backBearing_vibration_acc2': 0.09, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:07:02', 'spindleRunIn_speed_level': 7, 'spindleRunIn_speed': 7000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 44.1, 'spindleRunIn_outer_backBearing_temp': 26.1, 'spindleRunIn_room_temp': 26, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.065, 'spindleRunIn_frontBearing_vibration_acc1': 0.111, 'spindleRunIn_frontBearing_vibration_disp1': 0.4, 'spindleRunIn_frontBearing_vibration_speed2': 0.028, 'spindleRunIn_frontBearing_vibration_acc2': 0.068, 'spindleRunIn_frontBearing_vibration_disp2': 0.3, 'spindleRunIn_backBearing_vibration_speed1': 0.079, 'spindleRunIn_backBearing_vibration_acc1': 0.127, 'spindleRunIn_backBearing_vibration_disp1': 0.3, 'spindleRunIn_backBearing_vibration_speed2': 0.022, 'spindleRunIn_backBearing_vibration_acc2': 0.089, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:07:15', 'spindleRunIn_speed_level': 8, 'spindleRunIn_speed': 8000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 44.1, 'spindleRunIn_outer_backBearing_temp': 26.1, 'spindleRunIn_room_temp': 26, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.092, 'spindleRunIn_frontBearing_vibration_acc1': 0.13, 'spindleRunIn_frontBearing_vibration_disp1': 0.4, 'spindleRunIn_frontBearing_vibration_speed2': 0.028, 'spindleRunIn_frontBearing_vibration_acc2': 0.066, 'spindleRunIn_frontBearing_vibration_disp2': 0.2, 'spindleRunIn_backBearing_vibration_speed1': 0.1, 'spindleRunIn_backBearing_vibration_acc1': 0.123, 'spindleRunIn_backBearing_vibration_disp1': 0.3, 'spindleRunIn_backBearing_vibration_speed2': 0.022, 'spindleRunIn_backBearing_vibration_acc2': 0.088, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:07:28', 'spindleRunIn_speed_level': 9, 'spindleRunIn_speed': 9000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 44.1, 'spindleRunIn_outer_backBearing_temp': 26.1, 'spindleRunIn_room_temp': 26, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.093, 'spindleRunIn_frontBearing_vibration_acc1': 0.156, 'spindleRunIn_frontBearing_vibration_disp1': 0.5, 'spindleRunIn_frontBearing_vibration_speed2': 0.028, 'spindleRunIn_frontBearing_vibration_acc2': 0.065, 'spindleRunIn_frontBearing_vibration_disp2': 0.6, 'spindleRunIn_backBearing_vibration_speed1': 0.085, 'spindleRunIn_backBearing_vibration_acc1': 0.157, 'spindleRunIn_backBearing_vibration_disp1': 0.2, 'spindleRunIn_backBearing_vibration_speed2': 0.023, 'spindleRunIn_backBearing_vibration_acc2': 0.087, 'spindleRunIn_backBearing_vibration_disp2': 0.5 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:07:41', 'spindleRunIn_speed_level': 10, 'spindleRunIn_speed': 10000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 44.1, 'spindleRunIn_outer_backBearing_temp': 26, 'spindleRunIn_room_temp': 25.9, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.149, 'spindleRunIn_frontBearing_vibration_acc1': 0.206, 'spindleRunIn_frontBearing_vibration_disp1': 0.6, 'spindleRunIn_frontBearing_vibration_speed2': 0.025, 'spindleRunIn_frontBearing_vibration_acc2': 0.064, 'spindleRunIn_frontBearing_vibration_disp2': 0.3, 'spindleRunIn_backBearing_vibration_speed1': 0.083, 'spindleRunIn_backBearing_vibration_acc1': 0.188, 'spindleRunIn_backBearing_vibration_disp1': 0.2, 'spindleRunIn_backBearing_vibration_speed2': 0.02, 'spindleRunIn_backBearing_vibration_acc2': 0.086, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:07:55', 'spindleRunIn_speed_level': 11, 'spindleRunIn_speed': 11000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 44.1, 'spindleRunIn_outer_backBearing_temp': 26, 'spindleRunIn_room_temp': 25.9, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.119, 'spindleRunIn_frontBearing_vibration_acc1': 0.189, 'spindleRunIn_frontBearing_vibration_disp1': 0.5, 'spindleRunIn_frontBearing_vibration_speed2': 0.065, 'spindleRunIn_frontBearing_vibration_acc2': 0.063, 'spindleRunIn_frontBearing_vibration_disp2': 0.2, 'spindleRunIn_backBearing_vibration_speed1': 0.08, 'spindleRunIn_backBearing_vibration_acc1': 0.198, 'spindleRunIn_backBearing_vibration_disp1': 0.2, 'spindleRunIn_backBearing_vibration_speed2': 0.062, 'spindleRunIn_backBearing_vibration_acc2': 0.086, 'spindleRunIn_backBearing_vibration_disp2': 0.3 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:08:09', 'spindleRunIn_speed_level': 12, 'spindleRunIn_speed': 12000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 44, 'spindleRunIn_outer_backBearing_temp': 25.9, 'spindleRunIn_room_temp': 25.8, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.108, 'spindleRunIn_frontBearing_vibration_acc1': 0.158, 'spindleRunIn_frontBearing_vibration_disp1': 0.6, 'spindleRunIn_frontBearing_vibration_speed2': 0.025, 'spindleRunIn_frontBearing_vibration_acc2': 0.063, 'spindleRunIn_frontBearing_vibration_disp2': 0.3, 'spindleRunIn_backBearing_vibration_speed1': 0.086, 'spindleRunIn_backBearing_vibration_acc1': 0.203, 'spindleRunIn_backBearing_vibration_disp1': 0.3, 'spindleRunIn_backBearing_vibration_speed2': 0.019, 'spindleRunIn_backBearing_vibration_acc2': 0.086, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:08:22', 'spindleRunIn_speed_level': 13, 'spindleRunIn_speed': 13000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 44, 'spindleRunIn_outer_backBearing_temp': 25.9, 'spindleRunIn_room_temp': 25.9, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.12, 'spindleRunIn_frontBearing_vibration_acc1': 0.5, 'spindleRunIn_frontBearing_vibration_disp1': 0.4, 'spindleRunIn_frontBearing_vibration_speed2': 0.045, 'spindleRunIn_frontBearing_vibration_acc2': 0.062, 'spindleRunIn_frontBearing_vibration_disp2': 0.3, 'spindleRunIn_backBearing_vibration_speed1': 0.09, 'spindleRunIn_backBearing_vibration_acc1': 0.308, 'spindleRunIn_backBearing_vibration_disp1': 0.2, 'spindleRunIn_backBearing_vibration_speed2': 0.04, 'spindleRunIn_backBearing_vibration_acc2': 0.087, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:08:35', 'spindleRunIn_speed_level': 14, 'spindleRunIn_speed': 14000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 44, 'spindleRunIn_outer_backBearing_temp': 25.9, 'spindleRunIn_room_temp': 25.8, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.102, 'spindleRunIn_frontBearing_vibration_acc1': 0.306, 'spindleRunIn_frontBearing_vibration_disp1': 0.4, 'spindleRunIn_frontBearing_vibration_speed2': 0.034, 'spindleRunIn_frontBearing_vibration_acc2': 0.063, 'spindleRunIn_frontBearing_vibration_disp2': 0.3, 'spindleRunIn_backBearing_vibration_speed1': 0.092, 'spindleRunIn_backBearing_vibration_acc1': 0.182, 'spindleRunIn_backBearing_vibration_disp1': 0.2, 'spindleRunIn_backBearing_vibration_speed2': 0.029, 'spindleRunIn_backBearing_vibration_acc2': 0.089, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:08:48', 'spindleRunIn_speed_level': 15, 'spindleRunIn_speed': 15000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 43.9, 'spindleRunIn_outer_backBearing_temp': 25.9, 'spindleRunIn_room_temp': 25.8, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.119, 'spindleRunIn_frontBearing_vibration_acc1': 0.278, 'spindleRunIn_frontBearing_vibration_disp1': 0.5, 'spindleRunIn_frontBearing_vibration_speed2': 0.037, 'spindleRunIn_frontBearing_vibration_acc2': 0.068, 'spindleRunIn_frontBearing_vibration_disp2': 0.3, 'spindleRunIn_backBearing_vibration_speed1': 0.099, 'spindleRunIn_backBearing_vibration_acc1': 0.217, 'spindleRunIn_backBearing_vibration_disp1': 0.4, 'spindleRunIn_backBearing_vibration_speed2': 0.024, 'spindleRunIn_backBearing_vibration_acc2': 0.098, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:09:01', 'spindleRunIn_speed_level': 16, 'spindleRunIn_speed': 16000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 43.9, 'spindleRunIn_outer_backBearing_temp': 25.8, 'spindleRunIn_room_temp': 25.8, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.125, 'spindleRunIn_frontBearing_vibration_acc1': 0.34, 'spindleRunIn_frontBearing_vibration_disp1': 0.4, 'spindleRunIn_frontBearing_vibration_speed2': 0.036, 'spindleRunIn_frontBearing_vibration_acc2': 0.071, 'spindleRunIn_frontBearing_vibration_disp2': 0.3, 'spindleRunIn_backBearing_vibration_speed1': 0.135, 'spindleRunIn_backBearing_vibration_acc1': 0.219, 'spindleRunIn_backBearing_vibration_disp1': 0.3, 'spindleRunIn_backBearing_vibration_speed2': 0.022, 'spindleRunIn_backBearing_vibration_acc2': 0.103, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:09:14', 'spindleRunIn_speed_level': 17, 'spindleRunIn_speed': 17000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 43.9, 'spindleRunIn_outer_backBearing_temp': 25.9, 'spindleRunIn_room_temp': 25.8, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.119, 'spindleRunIn_frontBearing_vibration_acc1': 0.223, 'spindleRunIn_frontBearing_vibration_disp1': 0.4, 'spindleRunIn_frontBearing_vibration_speed2': 0.1, 'spindleRunIn_frontBearing_vibration_acc2': 0.074, 'spindleRunIn_frontBearing_vibration_disp2': 0.5, 'spindleRunIn_backBearing_vibration_speed1': 0.205, 'spindleRunIn_backBearing_vibration_acc1': 0.222, 'spindleRunIn_backBearing_vibration_disp1': 0.5, 'spindleRunIn_backBearing_vibration_speed2': 0.091, 'spindleRunIn_backBearing_vibration_acc2': 0.108, 'spindleRunIn_backBearing_vibration_disp2': 0.4 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:09:27', 'spindleRunIn_speed_level': 18, 'spindleRunIn_speed': 18000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 43.9, 'spindleRunIn_outer_backBearing_temp': 25.9, 'spindleRunIn_room_temp': 25.9, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.122, 'spindleRunIn_frontBearing_vibration_acc1': 0.25, 'spindleRunIn_frontBearing_vibration_disp1': 0.4, 'spindleRunIn_frontBearing_vibration_speed2': 0.037, 'spindleRunIn_frontBearing_vibration_acc2': 0.076, 'spindleRunIn_frontBearing_vibration_disp2': 0.4, 'spindleRunIn_backBearing_vibration_speed1': 0.195, 'spindleRunIn_backBearing_vibration_acc1': 0.237, 'spindleRunIn_backBearing_vibration_disp1': 0.4, 'spindleRunIn_backBearing_vibration_speed2': 0.022, 'spindleRunIn_backBearing_vibration_acc2': 0.112, 'spindleRunIn_backBearing_vibration_disp2': 0.3 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:09:41', 'spindleRunIn_speed_level': 19, 'spindleRunIn_speed': 19000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 43.9, 'spindleRunIn_outer_backBearing_temp': 25.9, 'spindleRunIn_room_temp': 25.8, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.126, 'spindleRunIn_frontBearing_vibration_acc1': 0.475, 'spindleRunIn_frontBearing_vibration_disp1': 0.4, 'spindleRunIn_frontBearing_vibration_speed2': 0.038, 'spindleRunIn_frontBearing_vibration_acc2': 0.078, 'spindleRunIn_frontBearing_vibration_disp2': 0.4, 'spindleRunIn_backBearing_vibration_speed1': 0.13, 'spindleRunIn_backBearing_vibration_acc1': 0.321, 'spindleRunIn_backBearing_vibration_disp1': 0.3, 'spindleRunIn_backBearing_vibration_speed2': 0.023, 'spindleRunIn_backBearing_vibration_acc2': 0.117, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:09:54', 'spindleRunIn_speed_level': 20, 'spindleRunIn_speed': 20000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 43.9, 'spindleRunIn_outer_backBearing_temp': 25.9, 'spindleRunIn_room_temp': 25.9, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.133, 'spindleRunIn_frontBearing_vibration_acc1': 0.86, 'spindleRunIn_frontBearing_vibration_disp1': 0.7, 'spindleRunIn_frontBearing_vibration_speed2': 0.038, 'spindleRunIn_frontBearing_vibration_acc2': 0.08, 'spindleRunIn_frontBearing_vibration_disp2': 0.3, 'spindleRunIn_backBearing_vibration_speed1': 0.16, 'spindleRunIn_backBearing_vibration_acc1': 0.342, 'spindleRunIn_backBearing_vibration_disp1': 0.7, 'spindleRunIn_backBearing_vibration_speed2': 0.024, 'spindleRunIn_backBearing_vibration_acc2': 0.12, 'spindleRunIn_backBearing_vibration_disp2': 0.3 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:10:07', 'spindleRunIn_speed_level': 21, 'spindleRunIn_speed': 21000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 43.9, 'spindleRunIn_outer_backBearing_temp': 25.9, 'spindleRunIn_room_temp': 25.9, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.187, 'spindleRunIn_frontBearing_vibration_acc1': 0.28, 'spindleRunIn_frontBearing_vibration_disp1': 0.5, 'spindleRunIn_frontBearing_vibration_speed2': 0.04, 'spindleRunIn_frontBearing_vibration_acc2': 0.082, 'spindleRunIn_frontBearing_vibration_disp2': 0.4, 'spindleRunIn_backBearing_vibration_speed1': 0.232, 'spindleRunIn_backBearing_vibration_acc1': 0.188, 'spindleRunIn_backBearing_vibration_disp1': 0.4, 'spindleRunIn_backBearing_vibration_speed2': 0.025, 'spindleRunIn_backBearing_vibration_acc2': 0.124, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:10:20', 'spindleRunIn_speed_level': 22, 'spindleRunIn_speed': 22000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 43.9, 'spindleRunIn_outer_backBearing_temp': 25.9, 'spindleRunIn_room_temp': 25.9, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.187, 'spindleRunIn_frontBearing_vibration_acc1': 0.28, 'spindleRunIn_frontBearing_vibration_disp1': 0.5, 'spindleRunIn_frontBearing_vibration_speed2': 0.04, 'spindleRunIn_frontBearing_vibration_acc2': 0.082, 'spindleRunIn_frontBearing_vibration_disp2': 0.4, 'spindleRunIn_backBearing_vibration_speed1': 0.232, 'spindleRunIn_backBearing_vibration_acc1': 0.188, 'spindleRunIn_backBearing_vibration_disp1': 0.4, 'spindleRunIn_backBearing_vibration_speed2': 0.025, 'spindleRunIn_backBearing_vibration_acc2': 0.124, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:10:34', 'spindleRunIn_speed_level': 23, 'spindleRunIn_speed': 23000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 44, 'spindleRunIn_outer_backBearing_temp': 26, 'spindleRunIn_room_temp': 26, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.094, 'spindleRunIn_frontBearing_vibration_acc1': 0.242, 'spindleRunIn_frontBearing_vibration_disp1': 0.4, 'spindleRunIn_frontBearing_vibration_speed2': 0.035, 'spindleRunIn_frontBearing_vibration_acc2': 0.087, 'spindleRunIn_frontBearing_vibration_disp2': 0.4, 'spindleRunIn_backBearing_vibration_speed1': 0.251, 'spindleRunIn_backBearing_vibration_acc1': 0.189, 'spindleRunIn_backBearing_vibration_disp1': 0.4, 'spindleRunIn_backBearing_vibration_speed2': 0.027, 'spindleRunIn_backBearing_vibration_acc2': 0.13, 'spindleRunIn_backBearing_vibration_disp2': 0.3 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:10:47', 'spindleRunIn_speed_level': 24, 'spindleRunIn_speed': 24000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 44, 'spindleRunIn_outer_backBearing_temp': 26, 'spindleRunIn_room_temp': 26, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.194, 'spindleRunIn_frontBearing_vibration_acc1': 0.318, 'spindleRunIn_frontBearing_vibration_disp1': 0.6, 'spindleRunIn_frontBearing_vibration_speed2': 0.038, 'spindleRunIn_frontBearing_vibration_acc2': 0.088, 'spindleRunIn_frontBearing_vibration_disp2': 0.5, 'spindleRunIn_backBearing_vibration_speed1': 0.21, 'spindleRunIn_backBearing_vibration_acc1': 0.2, 'spindleRunIn_backBearing_vibration_disp1': 0.8, 'spindleRunIn_backBearing_vibration_speed2': 0.023, 'spindleRunIn_backBearing_vibration_acc2': 0.131, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:11:00', 'spindleRunIn_speed_level': 25, 'spindleRunIn_speed': 25000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 44, 'spindleRunIn_outer_backBearing_temp': 26, 'spindleRunIn_room_temp': 25.9, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.104, 'spindleRunIn_frontBearing_vibration_acc1': 0.239, 'spindleRunIn_frontBearing_vibration_disp1': 0.4, 'spindleRunIn_frontBearing_vibration_speed2': 0.048, 'spindleRunIn_frontBearing_vibration_acc2': 0.088, 'spindleRunIn_frontBearing_vibration_disp2': 0.4, 'spindleRunIn_backBearing_vibration_speed1': 0.199, 'spindleRunIn_backBearing_vibration_acc1': 0.196, 'spindleRunIn_backBearing_vibration_disp1': 0.5, 'spindleRunIn_backBearing_vibration_speed2': 0.033, 'spindleRunIn_backBearing_vibration_acc2': 0.13, 'spindleRunIn_backBearing_vibration_disp2': 0.1 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:11:13', 'spindleRunIn_speed_level': 26, 'spindleRunIn_speed': 26000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 44, 'spindleRunIn_outer_backBearing_temp': 26, 'spindleRunIn_room_temp': 25.9, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.123, 'spindleRunIn_frontBearing_vibration_acc1': 0.226, 'spindleRunIn_frontBearing_vibration_disp1': 0.5, 'spindleRunIn_frontBearing_vibration_speed2': 0.039, 'spindleRunIn_frontBearing_vibration_acc2': 0.088, 'spindleRunIn_frontBearing_vibration_disp2': 0.3, 'spindleRunIn_backBearing_vibration_speed1': 0.257, 'spindleRunIn_backBearing_vibration_acc1': 0.195, 'spindleRunIn_backBearing_vibration_disp1': 0.4, 'spindleRunIn_backBearing_vibration_speed2': 0.025, 'spindleRunIn_backBearing_vibration_acc2': 0.127, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:11:26', 'spindleRunIn_speed_level': 27, 'spindleRunIn_speed': 27000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 44, 'spindleRunIn_outer_backBearing_temp': 26, 'spindleRunIn_room_temp': 25.9, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.155, 'spindleRunIn_frontBearing_vibration_acc1': 0.216, 'spindleRunIn_frontBearing_vibration_disp1': 0.4, 'spindleRunIn_frontBearing_vibration_speed2': 0.048, 'spindleRunIn_frontBearing_vibration_acc2': 0.087, 'spindleRunIn_frontBearing_vibration_disp2': 0.4, 'spindleRunIn_backBearing_vibration_speed1': 0.155, 'spindleRunIn_backBearing_vibration_acc1': 0.152, 'spindleRunIn_backBearing_vibration_disp1': 0.3, 'spindleRunIn_backBearing_vibration_speed2': 0.05, 'spindleRunIn_backBearing_vibration_acc2': 0.12, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:11:39', 'spindleRunIn_speed_level': 28, 'spindleRunIn_speed': 28000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 44, 'spindleRunIn_outer_backBearing_temp': 26, 'spindleRunIn_room_temp': 25.9, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.148, 'spindleRunIn_frontBearing_vibration_acc1': 0.223, 'spindleRunIn_frontBearing_vibration_disp1': 0.5, 'spindleRunIn_frontBearing_vibration_speed2': 0.051, 'spindleRunIn_frontBearing_vibration_acc2': 0.084, 'spindleRunIn_frontBearing_vibration_disp2': 0.3, 'spindleRunIn_backBearing_vibration_speed1': 0.278, 'spindleRunIn_backBearing_vibration_acc1': 0.165, 'spindleRunIn_backBearing_vibration_disp1': 0.4, 'spindleRunIn_backBearing_vibration_speed2': 0.06, 'spindleRunIn_backBearing_vibration_acc2': 0.112, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:11:53', 'spindleRunIn_speed_level': 29, 'spindleRunIn_speed': 29000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 43.9, 'spindleRunIn_outer_backBearing_temp': 25.9, 'spindleRunIn_room_temp': 25.8, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.191, 'spindleRunIn_frontBearing_vibration_acc1': 0.2, 'spindleRunIn_frontBearing_vibration_disp1': 0.3, 'spindleRunIn_frontBearing_vibration_speed2': 0.047, 'spindleRunIn_frontBearing_vibration_acc2': 0.075, 'spindleRunIn_frontBearing_vibration_disp2': 0.3, 'spindleRunIn_backBearing_vibration_speed1': 0.229, 'spindleRunIn_backBearing_vibration_acc1': 0.156, 'spindleRunIn_backBearing_vibration_disp1': 0.4, 'spindleRunIn_backBearing_vibration_speed2': 0.059, 'spindleRunIn_backBearing_vibration_acc2': 0.096, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
  {'spindleRunIn_id': 1, 'spindleRunIn_period': '11:12:06', 'spindleRunIn_speed_level': 30, 'spindleRunIn_speed': 30000, 'spindleRunIn_stator_temp': 0, 'spindleRunIn_inner_frontBearing_temp': 0, 'spindleRunIn_inner_backBearing_temp': 0, 'spindleRunIn_outer_frontBearing_temp': 43.9, 'spindleRunIn_outer_backBearing_temp': 25.9, 'spindleRunIn_room_temp': 25.8, 'spindleRunIn_coolWater_temp': 0, 'spindleRunIn_Rphase_current': 0, 'spindleRunIn_Sphase_current': 0, 'spindleRunIn_Tphase_current': 0, 'spindleRunIn_cool_pipeline_flow': 0, 'spindleRunIn_cool_pipeline_pressure': 0, 'spindleRunIn_frontBearing_vibration_speed1': 0.173, 'spindleRunIn_frontBearing_vibration_acc1': 0.254, 'spindleRunIn_frontBearing_vibration_disp1': 0.3, 'spindleRunIn_frontBearing_vibration_speed2': 0.052, 'spindleRunIn_frontBearing_vibration_acc2': 0.074, 'spindleRunIn_frontBearing_vibration_disp2': 0.3, 'spindleRunIn_backBearing_vibration_speed1': 0.297, 'spindleRunIn_backBearing_vibration_acc1': 0.156, 'spindleRunIn_backBearing_vibration_disp1': 0.5, 'spindleRunIn_backBearing_vibration_speed2': 0.062, 'spindleRunIn_backBearing_vibration_acc2': 0.095, 'spindleRunIn_backBearing_vibration_disp2': 0.2 },
]

#新增SPINDLE資料
runin_data_total_size = len(_obj)
_objects = []
#tt = 0
for x in range(runin_data_total_size):
  u = RunInData(
  spindleRunIn_id = _obj[x]['spindleRunIn_id'],
  spindleRunIn_period = _obj[x]['spindleRunIn_period'],
  spindleRunIn_speed_level = _obj[x]['spindleRunIn_speed_level'],
  spindleRunIn_speed = _obj[x]['spindleRunIn_speed'],
  spindleRunIn_stator_temp = _obj[x]['spindleRunIn_stator_temp'],
  spindleRunIn_inner_frontBearing_temp = _obj[x]['spindleRunIn_inner_frontBearing_temp'],
  spindleRunIn_inner_backBearing_temp = _obj[x]['spindleRunIn_inner_backBearing_temp'],
  spindleRunIn_outer_frontBearing_temp = _obj[x]['spindleRunIn_outer_frontBearing_temp'],
  spindleRunIn_outer_backBearing_temp = _obj[x]['spindleRunIn_outer_backBearing_temp'],
  spindleRunIn_room_temp = _obj[x]['spindleRunIn_room_temp'],
  spindleRunIn_coolWater_temp = _obj[x]['spindleRunIn_coolWater_temp'],
  spindleRunIn_Rphase_current = _obj[x]['spindleRunIn_Rphase_current'],
  spindleRunIn_Sphase_current = _obj[x]['spindleRunIn_Sphase_current'],
  spindleRunIn_Tphase_current = _obj[x]['spindleRunIn_Tphase_current'],
  spindleRunIn_cool_pipeline_flow = _obj[x]['spindleRunIn_cool_pipeline_flow'],
  spindleRunIn_cool_pipeline_pressure = _obj[x]['spindleRunIn_cool_pipeline_pressure'],
  spindleRunIn_frontBearing_vibration_speed1 = _obj[x]['spindleRunIn_frontBearing_vibration_speed1'],
  spindleRunIn_frontBearing_vibration_acc1 = _obj[x]['spindleRunIn_frontBearing_vibration_acc1'],
  spindleRunIn_frontBearing_vibration_disp1 = _obj[x]['spindleRunIn_frontBearing_vibration_disp1'],
  spindleRunIn_frontBearing_vibration_speed2 = _obj[x]['spindleRunIn_frontBearing_vibration_speed2'],
  spindleRunIn_frontBearing_vibration_acc2 = _obj[x]['spindleRunIn_frontBearing_vibration_acc2'],
  spindleRunIn_frontBearing_vibration_disp2 = _obj[x]['spindleRunIn_frontBearing_vibration_disp2'],
  spindleRunIn_backBearing_vibration_speed1 = _obj[x]['spindleRunIn_backBearing_vibration_speed1'],
  spindleRunIn_backBearing_vibration_acc1 = _obj[x]['spindleRunIn_backBearing_vibration_acc1'],
  spindleRunIn_backBearing_vibration_disp1 = _obj[x]['spindleRunIn_backBearing_vibration_disp1'],
  spindleRunIn_backBearing_vibration_speed2 = _obj[x]['spindleRunIn_backBearing_vibration_speed2'],
  spindleRunIn_backBearing_vibration_acc2 = _obj[x]['spindleRunIn_backBearing_vibration_acc2'],
  spindleRunIn_backBearing_vibration_disp2 = _obj[x]['spindleRunIn_backBearing_vibration_disp2'],
  )
  _objects.append(u)

s.bulk_save_objects(_objects)

try:
    s.commit()
except pymysql.err.IntegrityError as e:
    s.rollback()
except exc.IntegrityError as e:
    s.rollback()
except Exception as e:
    s.rollback()

print("insert RunInData is ok...")

# --------------------------

spindle_runin_records = s.query(SpindleRunIn).all()
runin_data_records = s.query(RunInData).all()
for array in runin_data_records:
  spindle_runin_records[0]._runin_data.append(array)

try:
    s.commit()
except pymysql.err.IntegrityError as e:
    s.rollback()
except exc.IntegrityError as e:
    s.rollback()
except Exception as e:
    s.rollback()

print("spindle_runin and runin_data combine ok...")


#===


'''
grid_records = s.query(Grid).all()
for grid in grid_records:
  if not grid._spindles:
    print("grid id", grid.id, 'nothing...')
    continue
  spindle_ids = ', '.join(str(spindle.id) for spindle in grid._spindles)
  print("grid id", grid.id, 'total spindle: ', len(grid._spindles), 'spind id', spindle_ids)
'''

'''
for grid in spindle_runin_records:
    spindle_count = s.query(func.count(association_table.c.spindle_id)).filter_by(grid_id=grid.id).scalar()
    print(f"Grid id {grid.id} has {spindle_count} associated spindles.")
'''

spindle_runin_records = s.query(SpindleRunIn).all()
print(f"spindle_runin has {len(spindle_runin_records[0]._runin_data)} associated runin_data.")

s.close()